on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install wheel
          pip install -r requirements-dev.txt -r requirements.txt

      - name: Test with pytest
        run: pytest --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2

      - name: Analysing the code with pylint
        run: pylint function cartola_draft tests
      - name: Analysing the code with mypy
        run: mypy function cartola_draft tests